include: package:lint/strict.yaml

linter:
  rules:
    - prefer_double_quotes

analyzer:
  language:
      strict-casts: true
      strict-raw-types: true
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  plugins:
    - custom_lint
