name: mk8se
description: A save editor for Mario Kart 8 (Wii U)
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  built_collection: ^5.1.1
  collection: ^1.18.0
  crc32_checksum: ^0.0.2
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.3
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.4.3
  meta: ^1.12.0
  package_info_plus: ^8.0.0
  riverpod: ^2.4.3
  universal_html: ^2.2.4
  url_launcher: ^6.1.14

dev_dependencies:
  custom_lint: ^0.6.4
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.3.0
  riverpod_lint: ^2.3.0

flutter:
  uses-material-design: true

  assets:
    - assets/userdata-empty.dat

flutter_launcher_icons:
  image_path: "assets/icon.png"
  windows:
    generate: true
  web:
    generate: true